# Generated by Django 4.2.1 on 2023-05-24 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35, verbose_name='Nome')),
                ('autor', models.CharField(max_length=20, verbose_name='Autor')),
                ('ano_publicacao', models.IntegerField(max_length=4, verbose_name='Ano de Publicação')),
                ('editora', models.CharField(max_length=20, verbose_name='Editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(verbose_name='Data de Empréstimo')),
                ('data_devolucao', models.DateField(verbose_name='Data de Devolução')),
                ('livro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.livro', verbose_name='livro')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
    ]
