# Generated by Django 4.2.1 on 2023-05-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Ano de Publicação'),
        ),
    ]
